// RootLayout.tsx
import ClientRootLayout from "@/components/utility/ClientRootLayout";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Giggle!",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ClientRootLayout>{children}</ClientRootLayout>
            </body>
        </html>
    );
}
