import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/utility/Navbar";
import SessionWrapper from "./SessionWrapper";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Giggle!",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <SessionWrapper>
                <body className={inter.className}>
                    <EdgeStoreProvider>
                        <Navbar />
                        {children}
                    </EdgeStoreProvider>
                </body>
            </SessionWrapper>
        </html>
    );
}
